### ISSUE TITLE
googlesearch module not found

### ISSUE THREAD

**Issue by viher3** [DiegoCaraballo/Email-extractor#1]
Hi,

I am trying to install 'googlesearch' module with pip but can't be found.

`sudo pip install googlesearch`

Returns this error

`Could not find a version that satisfies the requirement googlesearch (from versions: )
No matching distribution found for googlesearch`

What can I do?

Thanks

**Comment by DiegoCaraballo** [comment]
What version of Python are you using to run this?

**Comment by DiegoCaraballo** [comment]
sudo pip install google-search

**Comment by viher3** [comment]
> sudo pip install google-search

I have installed 'google-search' successfully, but now when I run _**python3 EmailExtractor.py**_, it shows me this error message:

> Traceback (most recent call last):
  File "EmailExtractor.py", line 6, in <module>
    from googlesearch import search
ImportError: cannot import name search

My version is Python 3.6.5

**Comment by DiegoCaraballo** [comment]
Hello, sorry for the delay, if you use windows try pip update and then:
pip3 install google

If you are in Linux, update pip and then:
$ sudo apt-get install python3-pip
$ sudo pip3 install google

It worked for me. Regards

**Comment by viher3** [comment]
It worked. Thanks.
