### ISSUE TITLE
google search

### ISSUE THREAD

**Issue by lordcharlx** [DiegoCaraballo/Email-extractor#2]
![screenshot at 2018-09-15 05-44-49](https://user-images.githubusercontent.com/5570136/45582589-92b3ad00-b8aa-11e8-89ad-7a42081ba2c2.png)

dunno why I'm getting this error

**Comment by DiegoCaraballo** [comment]
Hello, sorry for the delay, if you use windows try pip update and then:
pip3 install google

If you are in Linux, update pip and then:
$ sudo apt-get install python3-pip
$ sudo pip3 install google

It worked for me. Regards
