### ISSUE TITLE
HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by apdd2003** [DiegoCaraballo/Email-extractor#3]
for some URLs this error-HTTP Error 403: Forbidden- is shown. 
e.g. URL   https://www.jiophone.website/jio-dth-booking/

**Comment by apdd2003** [comment]
error gone by changing code in function:
```
from urllib.request import Request, urlopen
# Extrae los correos de una única URL
def extractOnlyUrl(url):
	try:
		print ("Searching emails... please wait")

		count = 0
		listUrl = []
		req = Request(url, headers={'User-Agent': 'Mozilla/5.0 (X11; U; Linux i686) Gecko/20071127 Firefox/2.0.0.11'})

		conn = urlopen(req)
```
it only collects emails which have hyperlinks... plain text emails are not detected

**Comment by DiegoCaraballo** [comment]
Excelente @apdd2003 Regards

**Comment by DiegoCaraballo** [comment]
@apdd2003 
This is probably because of mod_security or some similar server security feature which blocks known spider/bot user agents (urllib uses something like python urllib/3.3.0, it's easily detected)

Fix - I have added the UserAgent module to solve this problem. regards
