### ISSUE TITLE
Extractor is grabbing scaled images and some ideas

### ISSUE THREAD

**Issue by luluhoc** [DiegoCaraballo/Email-extractor#5]
Can you do something about extractor grabbing scaled images with name "example@2x.jpg" it would be really helpful.

The other idea is to put multiple keywords so the extractor will be working non stop scraping emails.
The daemon would be also helpful.

**Comment by DiegoCaraballo** [comment]
@luluhoc 
Hi, thanks for the recommendation.
The idea that I have is to remove the images, but I will add another option because I see that it can be useful.
The option to include several words I like, I will implement.
regards

**Comment by luluhoc** [comment]
@DiegoCaraballo Thanks for your response, I'm excited about the new features. 
I think the best it would either to add to only export emails to txt, or to add it to 6th option to delete all images.

You could also add the option to block websites, cause from what I've observed certain sites can freeze scraper, and as well some high ranked sites don't contain any emails to harvest so it is a waste of time. For now, if I want to block a website I block it in /etc/hosts, but It would be a nice feature.

The last idea I have is to add the option to choose from which google result harvester will start scanning for emails, cause sometimes high ranked sites are no use.

**Comment by guvern** [comment]
@DiegoCaraballo it's there any option to select different countries of the world ?

**Comment by DiegoCaraballo** [comment]
@guvern Not yet. It will be one of the next developments. Regards

**Comment by DiegoCaraballo** [comment]
Add in Issue #11
