### ISSUE TITLE
Unknown URL type and sites that hang scraper

### ISSUE THREAD

**Issue by luluhoc** [DiegoCaraballo/Email-extractor#7]
Hello,
I'm getting this error that stops the program from extracting emails.

```
unknown url type: 'robert@broofa.com'
Press enter to continue
```

There is also issue with some sites that hang scraper, I'm not sure if it can be overcome, but here are some examples of the sites maybe you can figure it out from it.

```Searching in #content
Searching in https://whyy.streamguys1.com/whyy-mp3

Searching in http://www.investor.reuters.com/business/BusCompanyOverview.aspx?t
icker=SCI&symbol=SCI&target=%2fbusiness%2fbuscompany%2fbuscompfake%2fbuscompove
rview

Searching in http://www.accuweather.com/en/us/jersey-city-nj/07306/weather-fore
cast/2735_pc

groupon.com


I'm getting also this error
`[Errno 104] Connection reset by peer`

**Comment by luluhoc** [comment]
Solution for 
`[Errno 104] Connection reset by peer`

[](https://stackoverflow.com/questions/20568216/python-handling-socket-error-errno-104-connection-reset-by-peer)

**Comment by DiegoCaraballo** [comment]
@luluhoc 
Hi, add a control for the broken urls in options 1, 2 and 3.
The operation is now a bit slower, but I will try to solve it when I switch to objects.
regards

**Comment by luluhoc** [comment]
Thanks man, keep up the great work

**Comment by luluhoc** [comment]
The problem still persists. 
I'm searching "funeral home new jersey"

I have run updated python script 2 times and the script is hanging on the same url.

`Searching in #
Searching in /notices/Alejandro-Hernandez
Searching in /notices/Patrick-Montella
Searching in /notices/Frank-Petrecca
Searching in /notices/Anthony-Ferlazzo
Searching in /notices/Alejandro-Hernandez
Searching in /notices/Patrick-Montella
Searching in /notices/Frank-Petrecca
Searching in /notices/Anthony-Ferlazzo
Searching in /notices/Warren-Vernon
Searching in /notices/Victoria-Rooney
Searching in /notices/Warren-Vernon
Searching in /notices/Victoria-Rooney
Searching in javascript:navigateTo('/mailinglist')
Searching in javascript:navigateTo('/listings')
Searching in /send-flowers
Searching in /mailinglist
Searching in /listings
Searching in /send-flowers
Searching in /our-facilities
Searching in /concierge-services
Searching in http://www.nfda.org/
Searching in http://www.nutleychamber.com/
86 - chamber@nutleychamber.com
87 - info@tempotherapy.com
Searching in https://web.njsfda.org/public/professional-home/about-njsfda/relat
ed-entities/njfds.aspx
Searching in https://web.njsfda.org/public/preplanning/preplanning-a-funeral/ch
eck-trust-balances-and-choices-tax-statements.aspx
Searching in https://www.facebook.com/pages/Biondi-Funeral-Home/154470051254851
Searching in http://www.accuweather.com/en/us/nutley-nj/07110/weather-forecast/
2709_pc`

**Comment by DiegoCaraballo** [comment]
Hello @luluhoc  , I'm gonna check it.

**Comment by DiegoCaraballo** [comment]
Hello @luluhoc ,
In the lines 837 and 876 add "timeout = 10" and test.
f = urllib.request.urlopen(req, timeout=10) 

Later I upload the changes with other fixes
 
Regards

**Comment by luluhoc** [comment]
Ok I'll change it and I'll try it out

**Comment by luluhoc** [comment]
It doesn't work
